services:
  postgres:
    image: postgres:16-alpine
    container_name: mediapulse-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: mediapulse-redis
    ports:
      - "${REDIS_PORT}"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  minio:
    image: chrislusf/seaweedfs:latest
    container_name: mediapulse-s3
    command: "server -s3"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9333"]
      interval: 10s
      timeout: 5s
      retries: 3

  createbuckets:
    image: alpine:3.19
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      apk add --no-cache curl && \
      curl -s https://dl.min.io/client/mc/release/linux-amd64/mc -o /usr/local/bin/mc && \
      chmod +x /usr/local/bin/mc && \
      until mc alias set myminio http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD; do
        echo 'Ожидание запуска MinIO...';
        sleep 1;
      done;
      mc mb --ignore-existing myminio/$$S3_BUCKET_NAME;
      echo 'Бакет успешно создан!';
      "

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: mediapulse-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=postgres
      - REDIS_HOST=redis
      - S3_ENDPOINT_URL=http://minio:9000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: mediapulse-worker
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=postgres
      - REDIS_HOST=redis
      - S3_ENDPOINT_URL=http://minio:9000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy

volumes:
  postgres_data:
  minio_data:
  redis_data: