"""Add storage_key and processed_key to media_tasks

Revision ID: 6e973cd2f30c
Revises: a04d752725fc
Create Date: 2026-09-25 10:00:00.473843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e973cd2f30c'
down_revision: Union[str, Sequence[str], None] = 'a04d752725fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_tasks', sa.Column('storage_key', sa.String(length=512), nullable=True))
    op.add_column('media_tasks', sa.Column('processed_key', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_tasks', 'processed_key')
    op.drop_column('media_tasks', 'storage_key')
    # ### end Alembic commands ###
