"""add is_public to media_tasks

Revision ID: 8eab61f8455e
Revises: 9894dfe7d259
Create Date: 2026-09-23 22:38:25.976461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8eab61f8455e'
down_revision: Union[str, Sequence[str], None] = '9894dfe7d259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_tasks', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.drop_column('media_tasks', 'error_message')
    op.drop_column('media_tasks', 'width')
    op.drop_column('media_tasks', 'created_at')
    op.drop_column('media_tasks', 'height')
    op.drop_column('media_tasks', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_tasks', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('media_tasks', sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('media_tasks', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('media_tasks', sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('media_tasks', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('media_tasks', 'is_public')
    # ### end Alembic commands ###
